// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: plugin/proto/engine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Engine_Type_FullMethodName           = "/dozeplugin.v1.Engine/Type"
	Engine_Capabilities_FullMethodName   = "/dozeplugin.v1.Engine/Capabilities"
	Engine_DecodeConfig_FullMethodName   = "/dozeplugin.v1.Engine/DecodeConfig"
	Engine_Resolve_FullMethodName        = "/dozeplugin.v1.Engine/Resolve"
	Engine_Provision_FullMethodName      = "/dozeplugin.v1.Engine/Provision"
	Engine_Provisioned_FullMethodName    = "/dozeplugin.v1.Engine/Provisioned"
	Engine_BackendSocket_FullMethodName  = "/dozeplugin.v1.Engine/BackendSocket"
	Engine_ConnString_FullMethodName     = "/dozeplugin.v1.Engine/ConnString"
	Engine_Plan_FullMethodName           = "/dozeplugin.v1.Engine/Plan"
	Engine_Converge_FullMethodName       = "/dozeplugin.v1.Engine/Converge"
	Engine_Objects_FullMethodName        = "/dozeplugin.v1.Engine/Objects"
	Engine_Prune_FullMethodName          = "/dozeplugin.v1.Engine/Prune"
	Engine_Attributes_FullMethodName     = "/dozeplugin.v1.Engine/Attributes"
	Engine_BackendURL_FullMethodName     = "/dozeplugin.v1.Engine/BackendURL"
	Engine_Supervised_FullMethodName     = "/dozeplugin.v1.Engine/Supervised"
	Engine_Hook_FullMethodName           = "/dozeplugin.v1.Engine/Hook"
	Engine_CheckHealth_FullMethodName    = "/dozeplugin.v1.Engine/CheckHealth"
	Engine_RestartPolicy_FullMethodName  = "/dozeplugin.v1.Engine/RestartPolicy"
	Engine_AdvertisedAddr_FullMethodName = "/dozeplugin.v1.Engine/AdvertisedAddr"
	Engine_EnsureTemplate_FullMethodName = "/dozeplugin.v1.Engine/EnsureTemplate"
	Engine_CloneTemplate_FullMethodName  = "/dozeplugin.v1.Engine/CloneTemplate"
	Engine_WireAddr_FullMethodName       = "/dozeplugin.v1.Engine/WireAddr"
	Engine_Actions_FullMethodName        = "/dozeplugin.v1.Engine/Actions"
	Engine_Resources_FullMethodName      = "/dozeplugin.v1.Engine/Resources"
	Engine_RunAction_FullMethodName      = "/dozeplugin.v1.Engine/RunAction"
)

// EngineClient is the client API for Engine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Engine is the contract every doze engine module implements as an out-of-process
// gRPC plugin (HashiCorp go-plugin). It is the wire serialization of the in-tree
// engine.Driver + capability interfaces: the plugin does the control-plane work and
// returns a SpawnPlan describing how to run; doze core owns supervision and the
// proxy. Optional capabilities are gated by Capabilities() so the host only calls
// what a plugin advertises.
type EngineClient interface {
	// Required.
	Type(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TypeResponse, error)
	Capabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	DecodeConfig(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error)
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	Provision(ctx context.Context, in *ProvisionRequest, opts ...grpc.CallOption) (*Empty, error)
	Provisioned(ctx context.Context, in *ProvisionedRequest, opts ...grpc.CallOption) (*ProvisionedResponse, error)
	BackendSocket(ctx context.Context, in *BackendSocketRequest, opts ...grpc.CallOption) (*BackendSocketResponse, error)
	ConnString(ctx context.Context, in *ConnStringRequest, opts ...grpc.CallOption) (*ConnStringResponse, error)
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*SpawnPlan, error)
	// Optional capabilities (advertised via Capabilities()).
	Converge(ctx context.Context, in *ConvergeRequest, opts ...grpc.CallOption) (*Empty, error)
	Objects(ctx context.Context, in *ObjectsRequest, opts ...grpc.CallOption) (*ObjectsResponse, error)
	Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*Empty, error)
	Attributes(ctx context.Context, in *AttributesRequest, opts ...grpc.CallOption) (*AttributesResponse, error)
	BackendURL(ctx context.Context, in *BackendURLRequest, opts ...grpc.CallOption) (*BackendURLResponse, error)
	Supervised(ctx context.Context, in *SupervisedRequest, opts ...grpc.CallOption) (*SupervisedResponse, error)
	Hook(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*Empty, error)
	CheckHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*Empty, error)
	RestartPolicy(ctx context.Context, in *RestartPolicyRequest, opts ...grpc.CallOption) (*RestartSpec, error)
	AdvertisedAddr(ctx context.Context, in *AddrRequest, opts ...grpc.CallOption) (*AddrResponse, error)
	EnsureTemplate(ctx context.Context, in *EnsureTemplateRequest, opts ...grpc.CallOption) (*Empty, error)
	CloneTemplate(ctx context.Context, in *CloneTemplateRequest, opts ...grpc.CallOption) (*Empty, error)
	WireAddr(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WireAddrResponse, error)
	Actions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionsResponse, error)
	Resources(ctx context.Context, in *ResourcesRequest, opts ...grpc.CallOption) (*ResourcesResponse, error)
	RunAction(ctx context.Context, in *RunActionRequest, opts ...grpc.CallOption) (*RunActionResponse, error)
}

type engineClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineClient(cc grpc.ClientConnInterface) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) Type(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeResponse)
	err := c.cc.Invoke(ctx, Engine_Type_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Capabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, Engine_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) DecodeConfig(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeResponse)
	err := c.cc.Invoke(ctx, Engine_DecodeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, Engine_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Provision(ctx context.Context, in *ProvisionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Engine_Provision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Provisioned(ctx context.Context, in *ProvisionedRequest, opts ...grpc.CallOption) (*ProvisionedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionedResponse)
	err := c.cc.Invoke(ctx, Engine_Provisioned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) BackendSocket(ctx context.Context, in *BackendSocketRequest, opts ...grpc.CallOption) (*BackendSocketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackendSocketResponse)
	err := c.cc.Invoke(ctx, Engine_BackendSocket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) ConnString(ctx context.Context, in *ConnStringRequest, opts ...grpc.CallOption) (*ConnStringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnStringResponse)
	err := c.cc.Invoke(ctx, Engine_ConnString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*SpawnPlan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnPlan)
	err := c.cc.Invoke(ctx, Engine_Plan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Converge(ctx context.Context, in *ConvergeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Engine_Converge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Objects(ctx context.Context, in *ObjectsRequest, opts ...grpc.CallOption) (*ObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectsResponse)
	err := c.cc.Invoke(ctx, Engine_Objects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Engine_Prune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Attributes(ctx context.Context, in *AttributesRequest, opts ...grpc.CallOption) (*AttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributesResponse)
	err := c.cc.Invoke(ctx, Engine_Attributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) BackendURL(ctx context.Context, in *BackendURLRequest, opts ...grpc.CallOption) (*BackendURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackendURLResponse)
	err := c.cc.Invoke(ctx, Engine_BackendURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Supervised(ctx context.Context, in *SupervisedRequest, opts ...grpc.CallOption) (*SupervisedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupervisedResponse)
	err := c.cc.Invoke(ctx, Engine_Supervised_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Hook(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Engine_Hook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) CheckHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Engine_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) RestartPolicy(ctx context.Context, in *RestartPolicyRequest, opts ...grpc.CallOption) (*RestartSpec, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartSpec)
	err := c.cc.Invoke(ctx, Engine_RestartPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) AdvertisedAddr(ctx context.Context, in *AddrRequest, opts ...grpc.CallOption) (*AddrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddrResponse)
	err := c.cc.Invoke(ctx, Engine_AdvertisedAddr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) EnsureTemplate(ctx context.Context, in *EnsureTemplateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Engine_EnsureTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) CloneTemplate(ctx context.Context, in *CloneTemplateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Engine_CloneTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) WireAddr(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WireAddrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireAddrResponse)
	err := c.cc.Invoke(ctx, Engine_WireAddr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Actions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionsResponse)
	err := c.cc.Invoke(ctx, Engine_Actions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Resources(ctx context.Context, in *ResourcesRequest, opts ...grpc.CallOption) (*ResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesResponse)
	err := c.cc.Invoke(ctx, Engine_Resources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) RunAction(ctx context.Context, in *RunActionRequest, opts ...grpc.CallOption) (*RunActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunActionResponse)
	err := c.cc.Invoke(ctx, Engine_RunAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServer is the server API for Engine service.
// All implementations must embed UnimplementedEngineServer
// for forward compatibility.
//
// Engine is the contract every doze engine module implements as an out-of-process
// gRPC plugin (HashiCorp go-plugin). It is the wire serialization of the in-tree
// engine.Driver + capability interfaces: the plugin does the control-plane work and
// returns a SpawnPlan describing how to run; doze core owns supervision and the
// proxy. Optional capabilities are gated by Capabilities() so the host only calls
// what a plugin advertises.
type EngineServer interface {
	// Required.
	Type(context.Context, *Empty) (*TypeResponse, error)
	Capabilities(context.Context, *Empty) (*CapabilitiesResponse, error)
	DecodeConfig(context.Context, *DecodeRequest) (*DecodeResponse, error)
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	Provision(context.Context, *ProvisionRequest) (*Empty, error)
	Provisioned(context.Context, *ProvisionedRequest) (*ProvisionedResponse, error)
	BackendSocket(context.Context, *BackendSocketRequest) (*BackendSocketResponse, error)
	ConnString(context.Context, *ConnStringRequest) (*ConnStringResponse, error)
	Plan(context.Context, *PlanRequest) (*SpawnPlan, error)
	// Optional capabilities (advertised via Capabilities()).
	Converge(context.Context, *ConvergeRequest) (*Empty, error)
	Objects(context.Context, *ObjectsRequest) (*ObjectsResponse, error)
	Prune(context.Context, *PruneRequest) (*Empty, error)
	Attributes(context.Context, *AttributesRequest) (*AttributesResponse, error)
	BackendURL(context.Context, *BackendURLRequest) (*BackendURLResponse, error)
	Supervised(context.Context, *SupervisedRequest) (*SupervisedResponse, error)
	Hook(context.Context, *HookRequest) (*Empty, error)
	CheckHealth(context.Context, *HealthRequest) (*Empty, error)
	RestartPolicy(context.Context, *RestartPolicyRequest) (*RestartSpec, error)
	AdvertisedAddr(context.Context, *AddrRequest) (*AddrResponse, error)
	EnsureTemplate(context.Context, *EnsureTemplateRequest) (*Empty, error)
	CloneTemplate(context.Context, *CloneTemplateRequest) (*Empty, error)
	WireAddr(context.Context, *Empty) (*WireAddrResponse, error)
	Actions(context.Context, *Empty) (*ActionsResponse, error)
	Resources(context.Context, *ResourcesRequest) (*ResourcesResponse, error)
	RunAction(context.Context, *RunActionRequest) (*RunActionResponse, error)
	mustEmbedUnimplementedEngineServer()
}

// UnimplementedEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServer struct{}

func (UnimplementedEngineServer) Type(context.Context, *Empty) (*TypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Type not implemented")
}
func (UnimplementedEngineServer) Capabilities(context.Context, *Empty) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedEngineServer) DecodeConfig(context.Context, *DecodeRequest) (*DecodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecodeConfig not implemented")
}
func (UnimplementedEngineServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedEngineServer) Provision(context.Context, *ProvisionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Provision not implemented")
}
func (UnimplementedEngineServer) Provisioned(context.Context, *ProvisionedRequest) (*ProvisionedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Provisioned not implemented")
}
func (UnimplementedEngineServer) BackendSocket(context.Context, *BackendSocketRequest) (*BackendSocketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BackendSocket not implemented")
}
func (UnimplementedEngineServer) ConnString(context.Context, *ConnStringRequest) (*ConnStringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnString not implemented")
}
func (UnimplementedEngineServer) Plan(context.Context, *PlanRequest) (*SpawnPlan, error) {
	return nil, status.Error(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedEngineServer) Converge(context.Context, *ConvergeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Converge not implemented")
}
func (UnimplementedEngineServer) Objects(context.Context, *ObjectsRequest) (*ObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Objects not implemented")
}
func (UnimplementedEngineServer) Prune(context.Context, *PruneRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Prune not implemented")
}
func (UnimplementedEngineServer) Attributes(context.Context, *AttributesRequest) (*AttributesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Attributes not implemented")
}
func (UnimplementedEngineServer) BackendURL(context.Context, *BackendURLRequest) (*BackendURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BackendURL not implemented")
}
func (UnimplementedEngineServer) Supervised(context.Context, *SupervisedRequest) (*SupervisedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Supervised not implemented")
}
func (UnimplementedEngineServer) Hook(context.Context, *HookRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Hook not implemented")
}
func (UnimplementedEngineServer) CheckHealth(context.Context, *HealthRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedEngineServer) RestartPolicy(context.Context, *RestartPolicyRequest) (*RestartSpec, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartPolicy not implemented")
}
func (UnimplementedEngineServer) AdvertisedAddr(context.Context, *AddrRequest) (*AddrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvertisedAddr not implemented")
}
func (UnimplementedEngineServer) EnsureTemplate(context.Context, *EnsureTemplateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureTemplate not implemented")
}
func (UnimplementedEngineServer) CloneTemplate(context.Context, *CloneTemplateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CloneTemplate not implemented")
}
func (UnimplementedEngineServer) WireAddr(context.Context, *Empty) (*WireAddrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WireAddr not implemented")
}
func (UnimplementedEngineServer) Actions(context.Context, *Empty) (*ActionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Actions not implemented")
}
func (UnimplementedEngineServer) Resources(context.Context, *ResourcesRequest) (*ResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resources not implemented")
}
func (UnimplementedEngineServer) RunAction(context.Context, *RunActionRequest) (*RunActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunAction not implemented")
}
func (UnimplementedEngineServer) mustEmbedUnimplementedEngineServer() {}
func (UnimplementedEngineServer) testEmbeddedByValue()                {}

// UnsafeEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServer will
// result in compilation errors.
type UnsafeEngineServer interface {
	mustEmbedUnimplementedEngineServer()
}

func RegisterEngineServer(s grpc.ServiceRegistrar, srv EngineServer) {
	// If the following call panics, it indicates UnimplementedEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Engine_ServiceDesc, srv)
}

func _Engine_Type_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Type(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Type_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Type(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Capabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_DecodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).DecodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_DecodeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).DecodeConfig(ctx, req.(*DecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Provision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Provision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Provision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Provision(ctx, req.(*ProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Provisioned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Provisioned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Provisioned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Provisioned(ctx, req.(*ProvisionedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_BackendSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackendSocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).BackendSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_BackendSocket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).BackendSocket(ctx, req.(*BackendSocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_ConnString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).ConnString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_ConnString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).ConnString(ctx, req.(*ConnStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Plan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Converge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Converge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Converge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Converge(ctx, req.(*ConvergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Objects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Objects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Objects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Objects(ctx, req.(*ObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Prune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Prune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Prune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Prune(ctx, req.(*PruneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Attributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Attributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Attributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Attributes(ctx, req.(*AttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_BackendURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackendURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).BackendURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_BackendURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).BackendURL(ctx, req.(*BackendURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Supervised_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupervisedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Supervised(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Supervised_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Supervised(ctx, req.(*SupervisedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Hook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Hook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Hook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Hook(ctx, req.(*HookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).CheckHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_RestartPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).RestartPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_RestartPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).RestartPolicy(ctx, req.(*RestartPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_AdvertisedAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).AdvertisedAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_AdvertisedAddr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).AdvertisedAddr(ctx, req.(*AddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_EnsureTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).EnsureTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_EnsureTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).EnsureTemplate(ctx, req.(*EnsureTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_CloneTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).CloneTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_CloneTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).CloneTemplate(ctx, req.(*CloneTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_WireAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).WireAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_WireAddr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).WireAddr(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Actions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Actions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Actions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Actions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Resources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Resources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Resources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Resources(ctx, req.(*ResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_RunAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).RunAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_RunAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).RunAction(ctx, req.(*RunActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Engine_ServiceDesc is the grpc.ServiceDesc for Engine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Engine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dozeplugin.v1.Engine",
	HandlerType: (*EngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Type",
			Handler:    _Engine_Type_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _Engine_Capabilities_Handler,
		},
		{
			MethodName: "DecodeConfig",
			Handler:    _Engine_DecodeConfig_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _Engine_Resolve_Handler,
		},
		{
			MethodName: "Provision",
			Handler:    _Engine_Provision_Handler,
		},
		{
			MethodName: "Provisioned",
			Handler:    _Engine_Provisioned_Handler,
		},
		{
			MethodName: "BackendSocket",
			Handler:    _Engine_BackendSocket_Handler,
		},
		{
			MethodName: "ConnString",
			Handler:    _Engine_ConnString_Handler,
		},
		{
			MethodName: "Plan",
			Handler:    _Engine_Plan_Handler,
		},
		{
			MethodName: "Converge",
			Handler:    _Engine_Converge_Handler,
		},
		{
			MethodName: "Objects",
			Handler:    _Engine_Objects_Handler,
		},
		{
			MethodName: "Prune",
			Handler:    _Engine_Prune_Handler,
		},
		{
			MethodName: "Attributes",
			Handler:    _Engine_Attributes_Handler,
		},
		{
			MethodName: "BackendURL",
			Handler:    _Engine_BackendURL_Handler,
		},
		{
			MethodName: "Supervised",
			Handler:    _Engine_Supervised_Handler,
		},
		{
			MethodName: "Hook",
			Handler:    _Engine_Hook_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _Engine_CheckHealth_Handler,
		},
		{
			MethodName: "RestartPolicy",
			Handler:    _Engine_RestartPolicy_Handler,
		},
		{
			MethodName: "AdvertisedAddr",
			Handler:    _Engine_AdvertisedAddr_Handler,
		},
		{
			MethodName: "EnsureTemplate",
			Handler:    _Engine_EnsureTemplate_Handler,
		},
		{
			MethodName: "CloneTemplate",
			Handler:    _Engine_CloneTemplate_Handler,
		},
		{
			MethodName: "WireAddr",
			Handler:    _Engine_WireAddr_Handler,
		},
		{
			MethodName: "Actions",
			Handler:    _Engine_Actions_Handler,
		},
		{
			MethodName: "Resources",
			Handler:    _Engine_Resources_Handler,
		},
		{
			MethodName: "RunAction",
			Handler:    _Engine_RunAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/proto/engine.proto",
}
