// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: plugin/proto/engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{0}
}

// ── value types (mirror internal/engine) ─────────────────────────────────────
type Platform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Triple        string                 `protobuf:"bytes,3,opt,name=triple,proto3" json:"triple,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_plugin_proto_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{1}
}

func (x *Platform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Platform) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Platform) GetTriple() string {
	if x != nil {
		return x.Triple
	}
	return ""
}

type Toolchain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	Full          string                 `protobuf:"bytes,2,opt,name=full,proto3" json:"full,omitempty"`
	BinDir        string                 `protobuf:"bytes,3,opt,name=bin_dir,json=binDir,proto3" json:"bin_dir,omitempty"`
	Tools         map[string]string      `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Toolchain) Reset() {
	*x = Toolchain{}
	mi := &file_plugin_proto_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Toolchain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toolchain) ProtoMessage() {}

func (x *Toolchain) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toolchain.ProtoReflect.Descriptor instead.
func (*Toolchain) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{2}
}

func (x *Toolchain) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *Toolchain) GetFull() string {
	if x != nil {
		return x.Full
	}
	return ""
}

func (x *Toolchain) GetBinDir() string {
	if x != nil {
		return x.BinDir
	}
	return ""
}

func (x *Toolchain) GetTools() map[string]string {
	if x != nil {
		return x.Tools
	}
	return nil
}

type Pin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolved      string                 `protobuf:"bytes,1,opt,name=resolved,proto3" json:"resolved,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Hashes        map[string]string      `protobuf:"bytes,3,rep,name=hashes,proto3" json:"hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pin) Reset() {
	*x = Pin{}
	mi := &file_plugin_proto_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pin) ProtoMessage() {}

func (x *Pin) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pin.ProtoReflect.Descriptor instead.
func (*Pin) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{3}
}

func (x *Pin) GetResolved() string {
	if x != nil {
		return x.Resolved
	}
	return ""
}

func (x *Pin) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Pin) GetHashes() map[string]string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

// LockEntry is one (engine, spec) -> pin row of the lockfile. Resolve round-trips
// a whole set of these so a composite engine's component pins (e.g. documentdb +
// ferretdb) each land under their own key instead of collapsing to one.
type LockEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	Spec          string                 `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Pin           *Pin                   `protobuf:"bytes,3,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockEntry) Reset() {
	*x = LockEntry{}
	mi := &file_plugin_proto_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockEntry) ProtoMessage() {}

func (x *LockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockEntry.ProtoReflect.Descriptor instead.
func (*LockEntry) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{4}
}

func (x *LockEntry) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *LockEntry) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *LockEntry) GetPin() *Pin {
	if x != nil {
		return x.Pin
	}
	return nil
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixSocket    string                 `protobuf:"bytes,1,opt,name=unix_socket,json=unixSocket,proto3" json:"unix_socket,omitempty"`
	TcpAddr       string                 `protobuf:"bytes,2,opt,name=tcp_addr,json=tcpAddr,proto3" json:"tcp_addr,omitempty"`
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_plugin_proto_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{5}
}

func (x *Endpoint) GetUnixSocket() string {
	if x != nil {
		return x.UnixSocket
	}
	return ""
}

func (x *Endpoint) GetTcpAddr() string {
	if x != nil {
		return x.TcpAddr
	}
	return ""
}

func (x *Endpoint) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type Dep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Engine        string                 `protobuf:"bytes,2,opt,name=engine,proto3" json:"engine,omitempty"`
	SocketDir     string                 `protobuf:"bytes,3,opt,name=socket_dir,json=socketDir,proto3" json:"socket_dir,omitempty"`
	Backend       string                 `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dep) Reset() {
	*x = Dep{}
	mi := &file_plugin_proto_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dep) ProtoMessage() {}

func (x *Dep) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dep.ProtoReflect.Descriptor instead.
func (*Dep) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{6}
}

func (x *Dep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dep) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *Dep) GetSocketDir() string {
	if x != nil {
		return x.SocketDir
	}
	return ""
}

func (x *Dep) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *Dep) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DataDir       string                 `protobuf:"bytes,4,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	SocketDir     string                 `protobuf:"bytes,5,opt,name=socket_dir,json=socketDir,proto3" json:"socket_dir,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,7,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Spec          []byte                 `protobuf:"bytes,8,opt,name=spec,proto3" json:"spec,omitempty"` // the plugin's own serialized config (opaque to core)
	Deps          map[string]*Dep        `protobuf:"bytes,9,rep,name=deps,proto3" json:"deps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_plugin_proto_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{7}
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instance) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Instance) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Instance) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *Instance) GetSocketDir() string {
	if x != nil {
		return x.SocketDir
	}
	return ""
}

func (x *Instance) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Instance) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *Instance) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Instance) GetDeps() map[string]*Dep {
	if x != nil {
		return x.Deps
	}
	return nil
}

type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // http | tcp | exec | log_line | socket
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	IntervalNs    int64                  `protobuf:"varint,3,opt,name=interval_ns,json=intervalNs,proto3" json:"interval_ns,omitempty"`
	TimeoutNs     int64                  `protobuf:"varint,4,opt,name=timeout_ns,json=timeoutNs,proto3" json:"timeout_ns,omitempty"`
	Retries       int32                  `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_plugin_proto_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{8}
}

func (x *Ready) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Ready) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Ready) GetIntervalNs() int64 {
	if x != nil {
		return x.IntervalNs
	}
	return 0
}

func (x *Ready) GetTimeoutNs() int64 {
	if x != nil {
		return x.TimeoutNs
	}
	return 0
}

func (x *Ready) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

type SpawnSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dir           string                 `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	Bin           string                 `protobuf:"bytes,3,opt,name=bin,proto3" json:"bin,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env           []string               `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	Tree          bool                   `protobuf:"varint,6,opt,name=tree,proto3" json:"tree,omitempty"`
	After         []string               `protobuf:"bytes,7,rep,name=after,proto3" json:"after,omitempty"`
	Ready         *Ready                 `protobuf:"bytes,8,opt,name=ready,proto3" json:"ready,omitempty"`
	Hooks         []string               `protobuf:"bytes,9,rep,name=hooks,proto3" json:"hooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnSpec) Reset() {
	*x = SpawnSpec{}
	mi := &file_plugin_proto_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnSpec) ProtoMessage() {}

func (x *SpawnSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnSpec.ProtoReflect.Descriptor instead.
func (*SpawnSpec) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{9}
}

func (x *SpawnSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpawnSpec) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *SpawnSpec) GetBin() string {
	if x != nil {
		return x.Bin
	}
	return ""
}

func (x *SpawnSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SpawnSpec) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SpawnSpec) GetTree() bool {
	if x != nil {
		return x.Tree
	}
	return false
}

func (x *SpawnSpec) GetAfter() []string {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *SpawnSpec) GetReady() *Ready {
	if x != nil {
		return x.Ready
	}
	return nil
}

func (x *SpawnSpec) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

type SpawnPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specs         []*SpawnSpec           `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnPlan) Reset() {
	*x = SpawnPlan{}
	mi := &file_plugin_proto_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnPlan) ProtoMessage() {}

func (x *SpawnPlan) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnPlan.ProtoReflect.Descriptor instead.
func (*SpawnPlan) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{10}
}

func (x *SpawnPlan) GetSpecs() []*SpawnSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type RestartSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        string                 `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	BackoffNs     int64                  `protobuf:"varint,2,opt,name=backoff_ns,json=backoffNs,proto3" json:"backoff_ns,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,3,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartSpec) Reset() {
	*x = RestartSpec{}
	mi := &file_plugin_proto_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartSpec) ProtoMessage() {}

func (x *RestartSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartSpec.ProtoReflect.Descriptor instead.
func (*RestartSpec) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{11}
}

func (x *RestartSpec) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *RestartSpec) GetBackoffNs() int64 {
	if x != nil {
		return x.BackoffNs
	}
	return 0
}

func (x *RestartSpec) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_plugin_proto_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{12}
}

func (x *Object) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Object) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Object) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// ── requests / responses ─────────────────────────────────────────────────────
type TypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeResponse) Reset() {
	*x = TypeResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeResponse) ProtoMessage() {}

func (x *TypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeResponse.ProtoReflect.Descriptor instead.
func (*TypeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{13}
}

func (x *TypeResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{14}
}

func (x *CapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type DecodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []byte                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`                                                                                     // the full source file declaring the block
	BlockType     string                 `protobuf:"bytes,2,opt,name=block_type,json=blockType,proto3" json:"block_type,omitempty"`                                                          // engine type (block keyword)
	BlockLabel    string                 `protobuf:"bytes,3,opt,name=block_label,json=blockLabel,proto3" json:"block_label,omitempty"`                                                       // instance name (block label)
	Variables     map[string][]byte      `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // eval-context vars, each ctyjson-encoded
	BaseDir       string                 `protobuf:"bytes,5,opt,name=base_dir,json=baseDir,proto3" json:"base_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeRequest) Reset() {
	*x = DecodeRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRequest) ProtoMessage() {}

func (x *DecodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRequest.ProtoReflect.Descriptor instead.
func (*DecodeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{15}
}

func (x *DecodeRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *DecodeRequest) GetBlockType() string {
	if x != nil {
		return x.BlockType
	}
	return ""
}

func (x *DecodeRequest) GetBlockLabel() string {
	if x != nil {
		return x.BlockLabel
	}
	return ""
}

func (x *DecodeRequest) GetVariables() map[string][]byte {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *DecodeRequest) GetBaseDir() string {
	if x != nil {
		return x.BaseDir
	}
	return ""
}

type DecodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          []byte                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeResponse) Reset() {
	*x = DecodeResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeResponse) ProtoMessage() {}

func (x *DecodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeResponse.ProtoReflect.Descriptor instead.
func (*DecodeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{16}
}

func (x *DecodeResponse) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          string                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Platform      *Platform              `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Locked        []*LockEntry           `protobuf:"bytes,3,rep,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{17}
}

func (x *ResolveRequest) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *ResolveRequest) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *ResolveRequest) GetLocked() []*LockEntry {
	if x != nil {
		return x.Locked
	}
	return nil
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Toolchain     *Toolchain             `protobuf:"bytes,1,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	Recorded      []*LockEntry           `protobuf:"bytes,2,rep,name=recorded,proto3" json:"recorded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{18}
}

func (x *ResolveResponse) GetToolchain() *Toolchain {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

func (x *ResolveResponse) GetRecorded() []*LockEntry {
	if x != nil {
		return x.Recorded
	}
	return nil
}

type ProvisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Toolchain     *Toolchain             `protobuf:"bytes,2,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{19}
}

func (x *ProvisionRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *ProvisionRequest) GetToolchain() *Toolchain {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

type ProvisionedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataDir       string                 `protobuf:"bytes,1,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionedRequest) Reset() {
	*x = ProvisionedRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionedRequest) ProtoMessage() {}

func (x *ProvisionedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionedRequest.ProtoReflect.Descriptor instead.
func (*ProvisionedRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{20}
}

func (x *ProvisionedRequest) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

type ProvisionedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provisioned   bool                   `protobuf:"varint,1,opt,name=provisioned,proto3" json:"provisioned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionedResponse) Reset() {
	*x = ProvisionedResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionedResponse) ProtoMessage() {}

func (x *ProvisionedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionedResponse.ProtoReflect.Descriptor instead.
func (*ProvisionedResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{21}
}

func (x *ProvisionedResponse) GetProvisioned() bool {
	if x != nil {
		return x.Provisioned
	}
	return false
}

type BackendSocketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SocketDir     string                 `protobuf:"bytes,1,opt,name=socket_dir,json=socketDir,proto3" json:"socket_dir,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendSocketRequest) Reset() {
	*x = BackendSocketRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendSocketRequest) ProtoMessage() {}

func (x *BackendSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendSocketRequest.ProtoReflect.Descriptor instead.
func (*BackendSocketRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{22}
}

func (x *BackendSocketRequest) GetSocketDir() string {
	if x != nil {
		return x.SocketDir
	}
	return ""
}

func (x *BackendSocketRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type BackendSocketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendSocketResponse) Reset() {
	*x = BackendSocketResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendSocketResponse) ProtoMessage() {}

func (x *BackendSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendSocketResponse.ProtoReflect.Descriptor instead.
func (*BackendSocketResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{23}
}

func (x *BackendSocketResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ConnStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnStringRequest) Reset() {
	*x = ConnStringRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnStringRequest) ProtoMessage() {}

func (x *ConnStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnStringRequest.ProtoReflect.Descriptor instead.
func (*ConnStringRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{24}
}

func (x *ConnStringRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *ConnStringRequest) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type ConnStringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvVar        string                 `protobuf:"bytes,1,opt,name=env_var,json=envVar,proto3" json:"env_var,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnStringResponse) Reset() {
	*x = ConnStringResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnStringResponse) ProtoMessage() {}

func (x *ConnStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnStringResponse.ProtoReflect.Descriptor instead.
func (*ConnStringResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{25}
}

func (x *ConnStringResponse) GetEnvVar() string {
	if x != nil {
		return x.EnvVar
	}
	return ""
}

func (x *ConnStringResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Toolchain     *Toolchain             `protobuf:"bytes,2,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{26}
}

func (x *PlanRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *PlanRequest) GetToolchain() *Toolchain {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

type EnsureTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Toolchain     *Toolchain             `protobuf:"bytes,1,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	TemplateDir   string                 `protobuf:"bytes,2,opt,name=template_dir,json=templateDir,proto3" json:"template_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureTemplateRequest) Reset() {
	*x = EnsureTemplateRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureTemplateRequest) ProtoMessage() {}

func (x *EnsureTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureTemplateRequest.ProtoReflect.Descriptor instead.
func (*EnsureTemplateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{27}
}

func (x *EnsureTemplateRequest) GetToolchain() *Toolchain {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

func (x *EnsureTemplateRequest) GetTemplateDir() string {
	if x != nil {
		return x.TemplateDir
	}
	return ""
}

type CloneTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateDir   string                 `protobuf:"bytes,1,opt,name=template_dir,json=templateDir,proto3" json:"template_dir,omitempty"`
	DestDir       string                 `protobuf:"bytes,2,opt,name=dest_dir,json=destDir,proto3" json:"dest_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneTemplateRequest) Reset() {
	*x = CloneTemplateRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneTemplateRequest) ProtoMessage() {}

func (x *CloneTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneTemplateRequest.ProtoReflect.Descriptor instead.
func (*CloneTemplateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{28}
}

func (x *CloneTemplateRequest) GetTemplateDir() string {
	if x != nil {
		return x.TemplateDir
	}
	return ""
}

func (x *CloneTemplateRequest) GetDestDir() string {
	if x != nil {
		return x.DestDir
	}
	return ""
}

// WireAddrResponse reports the unix socket the plugin listens on for client-fd
// handoff (SCM_RIGHTS). Empty path means the plugin runs no wire filter.
type WireAddrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireAddrResponse) Reset() {
	*x = WireAddrResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireAddrResponse) ProtoMessage() {}

func (x *WireAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireAddrResponse.ProtoReflect.Descriptor instead.
func (*WireAddrResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{29}
}

func (x *WireAddrResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ConvergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Toolchain     *Toolchain             `protobuf:"bytes,2,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvergeRequest) Reset() {
	*x = ConvergeRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvergeRequest) ProtoMessage() {}

func (x *ConvergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvergeRequest.ProtoReflect.Descriptor instead.
func (*ConvergeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{30}
}

func (x *ConvergeRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *ConvergeRequest) GetToolchain() *Toolchain {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

func (x *ConvergeRequest) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type ObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectsRequest) Reset() {
	*x = ObjectsRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectsRequest) ProtoMessage() {}

func (x *ObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectsRequest.ProtoReflect.Descriptor instead.
func (*ObjectsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{31}
}

func (x *ObjectsRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type ObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*Object              `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectsResponse) Reset() {
	*x = ObjectsResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectsResponse) ProtoMessage() {}

func (x *ObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectsResponse.ProtoReflect.Descriptor instead.
func (*ObjectsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{32}
}

func (x *ObjectsResponse) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type PruneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Toolchain     *Toolchain             `protobuf:"bytes,2,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Removed       []*Object              `protobuf:"bytes,4,rep,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneRequest) Reset() {
	*x = PruneRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneRequest) ProtoMessage() {}

func (x *PruneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneRequest.ProtoReflect.Descriptor instead.
func (*PruneRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{33}
}

func (x *PruneRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *PruneRequest) GetToolchain() *Toolchain {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

func (x *PruneRequest) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *PruneRequest) GetRemoved() []*Object {
	if x != nil {
		return x.Removed
	}
	return nil
}

type AttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributesRequest) Reset() {
	*x = AttributesRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributesRequest) ProtoMessage() {}

func (x *AttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributesRequest.ProtoReflect.Descriptor instead.
func (*AttributesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{34}
}

func (x *AttributesRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *AttributesRequest) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type AttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attrs         map[string][]byte      `protobuf:"bytes,1,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributesResponse) Reset() {
	*x = AttributesResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributesResponse) ProtoMessage() {}

func (x *AttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributesResponse.ProtoReflect.Descriptor instead.
func (*AttributesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{35}
}

func (x *AttributesResponse) GetAttrs() map[string][]byte {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type BackendURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendURLRequest) Reset() {
	*x = BackendURLRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendURLRequest) ProtoMessage() {}

func (x *BackendURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendURLRequest.ProtoReflect.Descriptor instead.
func (*BackendURLRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{36}
}

func (x *BackendURLRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type BackendURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendURLResponse) Reset() {
	*x = BackendURLResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendURLResponse) ProtoMessage() {}

func (x *BackendURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendURLResponse.ProtoReflect.Descriptor instead.
func (*BackendURLResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{37}
}

func (x *BackendURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SupervisedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisedRequest) Reset() {
	*x = SupervisedRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisedRequest) ProtoMessage() {}

func (x *SupervisedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisedRequest.ProtoReflect.Descriptor instead.
func (*SupervisedRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{38}
}

func (x *SupervisedRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type SupervisedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supervised    bool                   `protobuf:"varint,1,opt,name=supervised,proto3" json:"supervised,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisedResponse) Reset() {
	*x = SupervisedResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisedResponse) ProtoMessage() {}

func (x *SupervisedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisedResponse.ProtoReflect.Descriptor instead.
func (*SupervisedResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{39}
}

func (x *SupervisedResponse) GetSupervised() bool {
	if x != nil {
		return x.Supervised
	}
	return false
}

type HookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRequest) Reset() {
	*x = HookRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequest) ProtoMessage() {}

func (x *HookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequest.ProtoReflect.Descriptor instead.
func (*HookRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{40}
}

func (x *HookRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *HookRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{41}
}

func (x *HealthRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type RestartPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartPolicyRequest) Reset() {
	*x = RestartPolicyRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartPolicyRequest) ProtoMessage() {}

func (x *RestartPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartPolicyRequest.ProtoReflect.Descriptor instead.
func (*RestartPolicyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{42}
}

func (x *RestartPolicyRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type AddrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddrRequest) Reset() {
	*x = AddrRequest{}
	mi := &file_plugin_proto_engine_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrRequest) ProtoMessage() {}

func (x *AddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrRequest.ProtoReflect.Descriptor instead.
func (*AddrRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{43}
}

func (x *AddrRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type AddrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddrResponse) Reset() {
	*x = AddrResponse{}
	mi := &file_plugin_proto_engine_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrResponse) ProtoMessage() {}

func (x *AddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_engine_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrResponse.ProtoReflect.Descriptor instead.
func (*AddrResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_engine_proto_rawDescGZIP(), []int{44}
}

func (x *AddrResponse) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *AddrResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_plugin_proto_engine_proto protoreflect.FileDescriptor

const file_plugin_proto_engine_proto_rawDesc = "" +
	"\n" +
	"\x19plugin/proto/engine.proto\x12\rdozeplugin.v1\"\a\n" +
	"\x05Empty\"F\n" +
	"\bPlatform\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x16\n" +
	"\x06triple\x18\x03 \x01(\tR\x06triple\"\xc5\x01\n" +
	"\tToolchain\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\x12\n" +
	"\x04full\x18\x02 \x01(\tR\x04full\x12\x17\n" +
	"\abin_dir\x18\x03 \x01(\tR\x06binDir\x129\n" +
	"\x05tools\x18\x04 \x03(\v2#.dozeplugin.v1.Toolchain.ToolsEntryR\x05tools\x1a8\n" +
	"\n" +
	"ToolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x03Pin\x12\x1a\n" +
	"\bresolved\x18\x01 \x01(\tR\bresolved\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x126\n" +
	"\x06hashes\x18\x03 \x03(\v2\x1e.dozeplugin.v1.Pin.HashesEntryR\x06hashes\x1a9\n" +
	"\vHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\tLockEntry\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\x12\n" +
	"\x04spec\x18\x02 \x01(\tR\x04spec\x12$\n" +
	"\x03pin\x18\x03 \x01(\v2\x12.dozeplugin.v1.PinR\x03pin\"`\n" +
	"\bEndpoint\x12\x1f\n" +
	"\vunix_socket\x18\x01 \x01(\tR\n" +
	"unixSocket\x12\x19\n" +
	"\btcp_addr\x18\x02 \x01(\tR\atcpAddr\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\"|\n" +
	"\x03Dep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06engine\x18\x02 \x01(\tR\x06engine\x12\x1d\n" +
	"\n" +
	"socket_dir\x18\x03 \x01(\tR\tsocketDir\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"\xe7\x02\n" +
	"\bInstance\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x19\n" +
	"\bdata_dir\x18\x04 \x01(\tR\adataDir\x12\x1d\n" +
	"\n" +
	"socket_dir\x18\x05 \x01(\tR\tsocketDir\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x123\n" +
	"\bendpoint\x18\a \x01(\v2\x17.dozeplugin.v1.EndpointR\bendpoint\x12\x12\n" +
	"\x04spec\x18\b \x01(\fR\x04spec\x125\n" +
	"\x04deps\x18\t \x03(\v2!.dozeplugin.v1.Instance.DepsEntryR\x04deps\x1aK\n" +
	"\tDepsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.dozeplugin.v1.DepR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x05Ready\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1f\n" +
	"\vinterval_ns\x18\x03 \x01(\x03R\n" +
	"intervalNs\x12\x1d\n" +
	"\n" +
	"timeout_ns\x18\x04 \x01(\x03R\ttimeoutNs\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\"\xd5\x01\n" +
	"\tSpawnSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dir\x18\x02 \x01(\tR\x03dir\x12\x10\n" +
	"\x03bin\x18\x03 \x01(\tR\x03bin\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x10\n" +
	"\x03env\x18\x05 \x03(\tR\x03env\x12\x12\n" +
	"\x04tree\x18\x06 \x01(\bR\x04tree\x12\x14\n" +
	"\x05after\x18\a \x03(\tR\x05after\x12*\n" +
	"\x05ready\x18\b \x01(\v2\x14.dozeplugin.v1.ReadyR\x05ready\x12\x14\n" +
	"\x05hooks\x18\t \x03(\tR\x05hooks\";\n" +
	"\tSpawnPlan\x12.\n" +
	"\x05specs\x18\x01 \x03(\v2\x18.dozeplugin.v1.SpawnSpecR\x05specs\"e\n" +
	"\vRestartSpec\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\x12\x1d\n" +
	"\n" +
	"backoff_ns\x18\x02 \x01(\x03R\tbackoffNs\x12\x1f\n" +
	"\vmax_retries\x18\x03 \x01(\x05R\n" +
	"maxRetries\"D\n" +
	"\x06Object\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\"\"\n" +
	"\fTypeResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\":\n" +
	"\x14CapabilitiesResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\"\x87\x02\n" +
	"\rDecodeRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\x12\x1d\n" +
	"\n" +
	"block_type\x18\x02 \x01(\tR\tblockType\x12\x1f\n" +
	"\vblock_label\x18\x03 \x01(\tR\n" +
	"blockLabel\x12I\n" +
	"\tvariables\x18\x04 \x03(\v2+.dozeplugin.v1.DecodeRequest.VariablesEntryR\tvariables\x12\x19\n" +
	"\bbase_dir\x18\x05 \x01(\tR\abaseDir\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"$\n" +
	"\x0eDecodeResponse\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\"\x8b\x01\n" +
	"\x0eResolveRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\tR\x04spec\x123\n" +
	"\bplatform\x18\x02 \x01(\v2\x17.dozeplugin.v1.PlatformR\bplatform\x120\n" +
	"\x06locked\x18\x03 \x03(\v2\x18.dozeplugin.v1.LockEntryR\x06locked\"\x7f\n" +
	"\x0fResolveResponse\x126\n" +
	"\ttoolchain\x18\x01 \x01(\v2\x18.dozeplugin.v1.ToolchainR\ttoolchain\x124\n" +
	"\brecorded\x18\x02 \x03(\v2\x18.dozeplugin.v1.LockEntryR\brecorded\"\x7f\n" +
	"\x10ProvisionRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\x126\n" +
	"\ttoolchain\x18\x02 \x01(\v2\x18.dozeplugin.v1.ToolchainR\ttoolchain\"/\n" +
	"\x12ProvisionedRequest\x12\x19\n" +
	"\bdata_dir\x18\x01 \x01(\tR\adataDir\"7\n" +
	"\x13ProvisionedResponse\x12 \n" +
	"\vprovisioned\x18\x01 \x01(\bR\vprovisioned\"I\n" +
	"\x14BackendSocketRequest\x12\x1d\n" +
	"\n" +
	"socket_dir\x18\x01 \x01(\tR\tsocketDir\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"+\n" +
	"\x15BackendSocketResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"}\n" +
	"\x11ConnStringRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\x123\n" +
	"\bendpoint\x18\x02 \x01(\v2\x17.dozeplugin.v1.EndpointR\bendpoint\"?\n" +
	"\x12ConnStringResponse\x12\x17\n" +
	"\aenv_var\x18\x01 \x01(\tR\x06envVar\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"z\n" +
	"\vPlanRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\x126\n" +
	"\ttoolchain\x18\x02 \x01(\v2\x18.dozeplugin.v1.ToolchainR\ttoolchain\"r\n" +
	"\x15EnsureTemplateRequest\x126\n" +
	"\ttoolchain\x18\x01 \x01(\v2\x18.dozeplugin.v1.ToolchainR\ttoolchain\x12!\n" +
	"\ftemplate_dir\x18\x02 \x01(\tR\vtemplateDir\"T\n" +
	"\x14CloneTemplateRequest\x12!\n" +
	"\ftemplate_dir\x18\x01 \x01(\tR\vtemplateDir\x12\x19\n" +
	"\bdest_dir\x18\x02 \x01(\tR\adestDir\"&\n" +
	"\x10WireAddrResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xb3\x01\n" +
	"\x0fConvergeRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\x126\n" +
	"\ttoolchain\x18\x02 \x01(\v2\x18.dozeplugin.v1.ToolchainR\ttoolchain\x123\n" +
	"\bendpoint\x18\x03 \x01(\v2\x17.dozeplugin.v1.EndpointR\bendpoint\"E\n" +
	"\x0eObjectsRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\"B\n" +
	"\x0fObjectsResponse\x12/\n" +
	"\aobjects\x18\x01 \x03(\v2\x15.dozeplugin.v1.ObjectR\aobjects\"\xe1\x01\n" +
	"\fPruneRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\x126\n" +
	"\ttoolchain\x18\x02 \x01(\v2\x18.dozeplugin.v1.ToolchainR\ttoolchain\x123\n" +
	"\bendpoint\x18\x03 \x01(\v2\x17.dozeplugin.v1.EndpointR\bendpoint\x12/\n" +
	"\aremoved\x18\x04 \x03(\v2\x15.dozeplugin.v1.ObjectR\aremoved\"}\n" +
	"\x11AttributesRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\x123\n" +
	"\bendpoint\x18\x02 \x01(\v2\x17.dozeplugin.v1.EndpointR\bendpoint\"\x92\x01\n" +
	"\x12AttributesResponse\x12B\n" +
	"\x05attrs\x18\x01 \x03(\v2,.dozeplugin.v1.AttributesResponse.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"H\n" +
	"\x11BackendURLRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\"&\n" +
	"\x12BackendURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"H\n" +
	"\x11SupervisedRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\"4\n" +
	"\x12SupervisedResponse\x12\x1e\n" +
	"\n" +
	"supervised\x18\x01 \x01(\bR\n" +
	"supervised\"X\n" +
	"\vHookRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\"D\n" +
	"\rHealthRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\"K\n" +
	"\x14RestartPolicyRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\"B\n" +
	"\vAddrRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.dozeplugin.v1.InstanceR\binstance\"2\n" +
	"\fAddrResponse\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok2\xe4\f\n" +
	"\x06Engine\x129\n" +
	"\x04Type\x12\x14.dozeplugin.v1.Empty\x1a\x1b.dozeplugin.v1.TypeResponse\x12I\n" +
	"\fCapabilities\x12\x14.dozeplugin.v1.Empty\x1a#.dozeplugin.v1.CapabilitiesResponse\x12K\n" +
	"\fDecodeConfig\x12\x1c.dozeplugin.v1.DecodeRequest\x1a\x1d.dozeplugin.v1.DecodeResponse\x12H\n" +
	"\aResolve\x12\x1d.dozeplugin.v1.ResolveRequest\x1a\x1e.dozeplugin.v1.ResolveResponse\x12B\n" +
	"\tProvision\x12\x1f.dozeplugin.v1.ProvisionRequest\x1a\x14.dozeplugin.v1.Empty\x12T\n" +
	"\vProvisioned\x12!.dozeplugin.v1.ProvisionedRequest\x1a\".dozeplugin.v1.ProvisionedResponse\x12Z\n" +
	"\rBackendSocket\x12#.dozeplugin.v1.BackendSocketRequest\x1a$.dozeplugin.v1.BackendSocketResponse\x12Q\n" +
	"\n" +
	"ConnString\x12 .dozeplugin.v1.ConnStringRequest\x1a!.dozeplugin.v1.ConnStringResponse\x12<\n" +
	"\x04Plan\x12\x1a.dozeplugin.v1.PlanRequest\x1a\x18.dozeplugin.v1.SpawnPlan\x12@\n" +
	"\bConverge\x12\x1e.dozeplugin.v1.ConvergeRequest\x1a\x14.dozeplugin.v1.Empty\x12H\n" +
	"\aObjects\x12\x1d.dozeplugin.v1.ObjectsRequest\x1a\x1e.dozeplugin.v1.ObjectsResponse\x12:\n" +
	"\x05Prune\x12\x1b.dozeplugin.v1.PruneRequest\x1a\x14.dozeplugin.v1.Empty\x12Q\n" +
	"\n" +
	"Attributes\x12 .dozeplugin.v1.AttributesRequest\x1a!.dozeplugin.v1.AttributesResponse\x12Q\n" +
	"\n" +
	"BackendURL\x12 .dozeplugin.v1.BackendURLRequest\x1a!.dozeplugin.v1.BackendURLResponse\x12Q\n" +
	"\n" +
	"Supervised\x12 .dozeplugin.v1.SupervisedRequest\x1a!.dozeplugin.v1.SupervisedResponse\x128\n" +
	"\x04Hook\x12\x1a.dozeplugin.v1.HookRequest\x1a\x14.dozeplugin.v1.Empty\x12A\n" +
	"\vCheckHealth\x12\x1c.dozeplugin.v1.HealthRequest\x1a\x14.dozeplugin.v1.Empty\x12P\n" +
	"\rRestartPolicy\x12#.dozeplugin.v1.RestartPolicyRequest\x1a\x1a.dozeplugin.v1.RestartSpec\x12I\n" +
	"\x0eAdvertisedAddr\x12\x1a.dozeplugin.v1.AddrRequest\x1a\x1b.dozeplugin.v1.AddrResponse\x12L\n" +
	"\x0eEnsureTemplate\x12$.dozeplugin.v1.EnsureTemplateRequest\x1a\x14.dozeplugin.v1.Empty\x12J\n" +
	"\rCloneTemplate\x12#.dozeplugin.v1.CloneTemplateRequest\x1a\x14.dozeplugin.v1.Empty\x12A\n" +
	"\bWireAddr\x12\x14.dozeplugin.v1.Empty\x1a\x1f.dozeplugin.v1.WireAddrResponseB2Z0github.com/nerdmenot/doze-sdk/plugin/proto;protob\x06proto3"

var (
	file_plugin_proto_engine_proto_rawDescOnce sync.Once
	file_plugin_proto_engine_proto_rawDescData []byte
)

func file_plugin_proto_engine_proto_rawDescGZIP() []byte {
	file_plugin_proto_engine_proto_rawDescOnce.Do(func() {
		file_plugin_proto_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_engine_proto_rawDesc), len(file_plugin_proto_engine_proto_rawDesc)))
	})
	return file_plugin_proto_engine_proto_rawDescData
}

var file_plugin_proto_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_plugin_proto_engine_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: dozeplugin.v1.Empty
	(*Platform)(nil),              // 1: dozeplugin.v1.Platform
	(*Toolchain)(nil),             // 2: dozeplugin.v1.Toolchain
	(*Pin)(nil),                   // 3: dozeplugin.v1.Pin
	(*LockEntry)(nil),             // 4: dozeplugin.v1.LockEntry
	(*Endpoint)(nil),              // 5: dozeplugin.v1.Endpoint
	(*Dep)(nil),                   // 6: dozeplugin.v1.Dep
	(*Instance)(nil),              // 7: dozeplugin.v1.Instance
	(*Ready)(nil),                 // 8: dozeplugin.v1.Ready
	(*SpawnSpec)(nil),             // 9: dozeplugin.v1.SpawnSpec
	(*SpawnPlan)(nil),             // 10: dozeplugin.v1.SpawnPlan
	(*RestartSpec)(nil),           // 11: dozeplugin.v1.RestartSpec
	(*Object)(nil),                // 12: dozeplugin.v1.Object
	(*TypeResponse)(nil),          // 13: dozeplugin.v1.TypeResponse
	(*CapabilitiesResponse)(nil),  // 14: dozeplugin.v1.CapabilitiesResponse
	(*DecodeRequest)(nil),         // 15: dozeplugin.v1.DecodeRequest
	(*DecodeResponse)(nil),        // 16: dozeplugin.v1.DecodeResponse
	(*ResolveRequest)(nil),        // 17: dozeplugin.v1.ResolveRequest
	(*ResolveResponse)(nil),       // 18: dozeplugin.v1.ResolveResponse
	(*ProvisionRequest)(nil),      // 19: dozeplugin.v1.ProvisionRequest
	(*ProvisionedRequest)(nil),    // 20: dozeplugin.v1.ProvisionedRequest
	(*ProvisionedResponse)(nil),   // 21: dozeplugin.v1.ProvisionedResponse
	(*BackendSocketRequest)(nil),  // 22: dozeplugin.v1.BackendSocketRequest
	(*BackendSocketResponse)(nil), // 23: dozeplugin.v1.BackendSocketResponse
	(*ConnStringRequest)(nil),     // 24: dozeplugin.v1.ConnStringRequest
	(*ConnStringResponse)(nil),    // 25: dozeplugin.v1.ConnStringResponse
	(*PlanRequest)(nil),           // 26: dozeplugin.v1.PlanRequest
	(*EnsureTemplateRequest)(nil), // 27: dozeplugin.v1.EnsureTemplateRequest
	(*CloneTemplateRequest)(nil),  // 28: dozeplugin.v1.CloneTemplateRequest
	(*WireAddrResponse)(nil),      // 29: dozeplugin.v1.WireAddrResponse
	(*ConvergeRequest)(nil),       // 30: dozeplugin.v1.ConvergeRequest
	(*ObjectsRequest)(nil),        // 31: dozeplugin.v1.ObjectsRequest
	(*ObjectsResponse)(nil),       // 32: dozeplugin.v1.ObjectsResponse
	(*PruneRequest)(nil),          // 33: dozeplugin.v1.PruneRequest
	(*AttributesRequest)(nil),     // 34: dozeplugin.v1.AttributesRequest
	(*AttributesResponse)(nil),    // 35: dozeplugin.v1.AttributesResponse
	(*BackendURLRequest)(nil),     // 36: dozeplugin.v1.BackendURLRequest
	(*BackendURLResponse)(nil),    // 37: dozeplugin.v1.BackendURLResponse
	(*SupervisedRequest)(nil),     // 38: dozeplugin.v1.SupervisedRequest
	(*SupervisedResponse)(nil),    // 39: dozeplugin.v1.SupervisedResponse
	(*HookRequest)(nil),           // 40: dozeplugin.v1.HookRequest
	(*HealthRequest)(nil),         // 41: dozeplugin.v1.HealthRequest
	(*RestartPolicyRequest)(nil),  // 42: dozeplugin.v1.RestartPolicyRequest
	(*AddrRequest)(nil),           // 43: dozeplugin.v1.AddrRequest
	(*AddrResponse)(nil),          // 44: dozeplugin.v1.AddrResponse
	nil,                           // 45: dozeplugin.v1.Toolchain.ToolsEntry
	nil,                           // 46: dozeplugin.v1.Pin.HashesEntry
	nil,                           // 47: dozeplugin.v1.Instance.DepsEntry
	nil,                           // 48: dozeplugin.v1.DecodeRequest.VariablesEntry
	nil,                           // 49: dozeplugin.v1.AttributesResponse.AttrsEntry
}
var file_plugin_proto_engine_proto_depIdxs = []int32{
	45, // 0: dozeplugin.v1.Toolchain.tools:type_name -> dozeplugin.v1.Toolchain.ToolsEntry
	46, // 1: dozeplugin.v1.Pin.hashes:type_name -> dozeplugin.v1.Pin.HashesEntry
	3,  // 2: dozeplugin.v1.LockEntry.pin:type_name -> dozeplugin.v1.Pin
	5,  // 3: dozeplugin.v1.Instance.endpoint:type_name -> dozeplugin.v1.Endpoint
	47, // 4: dozeplugin.v1.Instance.deps:type_name -> dozeplugin.v1.Instance.DepsEntry
	8,  // 5: dozeplugin.v1.SpawnSpec.ready:type_name -> dozeplugin.v1.Ready
	9,  // 6: dozeplugin.v1.SpawnPlan.specs:type_name -> dozeplugin.v1.SpawnSpec
	48, // 7: dozeplugin.v1.DecodeRequest.variables:type_name -> dozeplugin.v1.DecodeRequest.VariablesEntry
	1,  // 8: dozeplugin.v1.ResolveRequest.platform:type_name -> dozeplugin.v1.Platform
	4,  // 9: dozeplugin.v1.ResolveRequest.locked:type_name -> dozeplugin.v1.LockEntry
	2,  // 10: dozeplugin.v1.ResolveResponse.toolchain:type_name -> dozeplugin.v1.Toolchain
	4,  // 11: dozeplugin.v1.ResolveResponse.recorded:type_name -> dozeplugin.v1.LockEntry
	7,  // 12: dozeplugin.v1.ProvisionRequest.instance:type_name -> dozeplugin.v1.Instance
	2,  // 13: dozeplugin.v1.ProvisionRequest.toolchain:type_name -> dozeplugin.v1.Toolchain
	7,  // 14: dozeplugin.v1.ConnStringRequest.instance:type_name -> dozeplugin.v1.Instance
	5,  // 15: dozeplugin.v1.ConnStringRequest.endpoint:type_name -> dozeplugin.v1.Endpoint
	7,  // 16: dozeplugin.v1.PlanRequest.instance:type_name -> dozeplugin.v1.Instance
	2,  // 17: dozeplugin.v1.PlanRequest.toolchain:type_name -> dozeplugin.v1.Toolchain
	2,  // 18: dozeplugin.v1.EnsureTemplateRequest.toolchain:type_name -> dozeplugin.v1.Toolchain
	7,  // 19: dozeplugin.v1.ConvergeRequest.instance:type_name -> dozeplugin.v1.Instance
	2,  // 20: dozeplugin.v1.ConvergeRequest.toolchain:type_name -> dozeplugin.v1.Toolchain
	5,  // 21: dozeplugin.v1.ConvergeRequest.endpoint:type_name -> dozeplugin.v1.Endpoint
	7,  // 22: dozeplugin.v1.ObjectsRequest.instance:type_name -> dozeplugin.v1.Instance
	12, // 23: dozeplugin.v1.ObjectsResponse.objects:type_name -> dozeplugin.v1.Object
	7,  // 24: dozeplugin.v1.PruneRequest.instance:type_name -> dozeplugin.v1.Instance
	2,  // 25: dozeplugin.v1.PruneRequest.toolchain:type_name -> dozeplugin.v1.Toolchain
	5,  // 26: dozeplugin.v1.PruneRequest.endpoint:type_name -> dozeplugin.v1.Endpoint
	12, // 27: dozeplugin.v1.PruneRequest.removed:type_name -> dozeplugin.v1.Object
	7,  // 28: dozeplugin.v1.AttributesRequest.instance:type_name -> dozeplugin.v1.Instance
	5,  // 29: dozeplugin.v1.AttributesRequest.endpoint:type_name -> dozeplugin.v1.Endpoint
	49, // 30: dozeplugin.v1.AttributesResponse.attrs:type_name -> dozeplugin.v1.AttributesResponse.AttrsEntry
	7,  // 31: dozeplugin.v1.BackendURLRequest.instance:type_name -> dozeplugin.v1.Instance
	7,  // 32: dozeplugin.v1.SupervisedRequest.instance:type_name -> dozeplugin.v1.Instance
	7,  // 33: dozeplugin.v1.HookRequest.instance:type_name -> dozeplugin.v1.Instance
	7,  // 34: dozeplugin.v1.HealthRequest.instance:type_name -> dozeplugin.v1.Instance
	7,  // 35: dozeplugin.v1.RestartPolicyRequest.instance:type_name -> dozeplugin.v1.Instance
	7,  // 36: dozeplugin.v1.AddrRequest.instance:type_name -> dozeplugin.v1.Instance
	6,  // 37: dozeplugin.v1.Instance.DepsEntry.value:type_name -> dozeplugin.v1.Dep
	0,  // 38: dozeplugin.v1.Engine.Type:input_type -> dozeplugin.v1.Empty
	0,  // 39: dozeplugin.v1.Engine.Capabilities:input_type -> dozeplugin.v1.Empty
	15, // 40: dozeplugin.v1.Engine.DecodeConfig:input_type -> dozeplugin.v1.DecodeRequest
	17, // 41: dozeplugin.v1.Engine.Resolve:input_type -> dozeplugin.v1.ResolveRequest
	19, // 42: dozeplugin.v1.Engine.Provision:input_type -> dozeplugin.v1.ProvisionRequest
	20, // 43: dozeplugin.v1.Engine.Provisioned:input_type -> dozeplugin.v1.ProvisionedRequest
	22, // 44: dozeplugin.v1.Engine.BackendSocket:input_type -> dozeplugin.v1.BackendSocketRequest
	24, // 45: dozeplugin.v1.Engine.ConnString:input_type -> dozeplugin.v1.ConnStringRequest
	26, // 46: dozeplugin.v1.Engine.Plan:input_type -> dozeplugin.v1.PlanRequest
	30, // 47: dozeplugin.v1.Engine.Converge:input_type -> dozeplugin.v1.ConvergeRequest
	31, // 48: dozeplugin.v1.Engine.Objects:input_type -> dozeplugin.v1.ObjectsRequest
	33, // 49: dozeplugin.v1.Engine.Prune:input_type -> dozeplugin.v1.PruneRequest
	34, // 50: dozeplugin.v1.Engine.Attributes:input_type -> dozeplugin.v1.AttributesRequest
	36, // 51: dozeplugin.v1.Engine.BackendURL:input_type -> dozeplugin.v1.BackendURLRequest
	38, // 52: dozeplugin.v1.Engine.Supervised:input_type -> dozeplugin.v1.SupervisedRequest
	40, // 53: dozeplugin.v1.Engine.Hook:input_type -> dozeplugin.v1.HookRequest
	41, // 54: dozeplugin.v1.Engine.CheckHealth:input_type -> dozeplugin.v1.HealthRequest
	42, // 55: dozeplugin.v1.Engine.RestartPolicy:input_type -> dozeplugin.v1.RestartPolicyRequest
	43, // 56: dozeplugin.v1.Engine.AdvertisedAddr:input_type -> dozeplugin.v1.AddrRequest
	27, // 57: dozeplugin.v1.Engine.EnsureTemplate:input_type -> dozeplugin.v1.EnsureTemplateRequest
	28, // 58: dozeplugin.v1.Engine.CloneTemplate:input_type -> dozeplugin.v1.CloneTemplateRequest
	0,  // 59: dozeplugin.v1.Engine.WireAddr:input_type -> dozeplugin.v1.Empty
	13, // 60: dozeplugin.v1.Engine.Type:output_type -> dozeplugin.v1.TypeResponse
	14, // 61: dozeplugin.v1.Engine.Capabilities:output_type -> dozeplugin.v1.CapabilitiesResponse
	16, // 62: dozeplugin.v1.Engine.DecodeConfig:output_type -> dozeplugin.v1.DecodeResponse
	18, // 63: dozeplugin.v1.Engine.Resolve:output_type -> dozeplugin.v1.ResolveResponse
	0,  // 64: dozeplugin.v1.Engine.Provision:output_type -> dozeplugin.v1.Empty
	21, // 65: dozeplugin.v1.Engine.Provisioned:output_type -> dozeplugin.v1.ProvisionedResponse
	23, // 66: dozeplugin.v1.Engine.BackendSocket:output_type -> dozeplugin.v1.BackendSocketResponse
	25, // 67: dozeplugin.v1.Engine.ConnString:output_type -> dozeplugin.v1.ConnStringResponse
	10, // 68: dozeplugin.v1.Engine.Plan:output_type -> dozeplugin.v1.SpawnPlan
	0,  // 69: dozeplugin.v1.Engine.Converge:output_type -> dozeplugin.v1.Empty
	32, // 70: dozeplugin.v1.Engine.Objects:output_type -> dozeplugin.v1.ObjectsResponse
	0,  // 71: dozeplugin.v1.Engine.Prune:output_type -> dozeplugin.v1.Empty
	35, // 72: dozeplugin.v1.Engine.Attributes:output_type -> dozeplugin.v1.AttributesResponse
	37, // 73: dozeplugin.v1.Engine.BackendURL:output_type -> dozeplugin.v1.BackendURLResponse
	39, // 74: dozeplugin.v1.Engine.Supervised:output_type -> dozeplugin.v1.SupervisedResponse
	0,  // 75: dozeplugin.v1.Engine.Hook:output_type -> dozeplugin.v1.Empty
	0,  // 76: dozeplugin.v1.Engine.CheckHealth:output_type -> dozeplugin.v1.Empty
	11, // 77: dozeplugin.v1.Engine.RestartPolicy:output_type -> dozeplugin.v1.RestartSpec
	44, // 78: dozeplugin.v1.Engine.AdvertisedAddr:output_type -> dozeplugin.v1.AddrResponse
	0,  // 79: dozeplugin.v1.Engine.EnsureTemplate:output_type -> dozeplugin.v1.Empty
	0,  // 80: dozeplugin.v1.Engine.CloneTemplate:output_type -> dozeplugin.v1.Empty
	29, // 81: dozeplugin.v1.Engine.WireAddr:output_type -> dozeplugin.v1.WireAddrResponse
	60, // [60:82] is the sub-list for method output_type
	38, // [38:60] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_plugin_proto_engine_proto_init() }
func file_plugin_proto_engine_proto_init() {
	if File_plugin_proto_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_engine_proto_rawDesc), len(file_plugin_proto_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_engine_proto_goTypes,
		DependencyIndexes: file_plugin_proto_engine_proto_depIdxs,
		MessageInfos:      file_plugin_proto_engine_proto_msgTypes,
	}.Build()
	File_plugin_proto_engine_proto = out.File
	file_plugin_proto_engine_proto_goTypes = nil
	file_plugin_proto_engine_proto_depIdxs = nil
}
